### ISSUE TITLE
Appendix, Unit testの実行結果について

### ISSUE THREAD

**Issue by yyamma** [yyamma/Intern-test-environment-manager#2]
4.Noteの項目のHow to testで、$ python3 -m pytest test_machine_info.pyと$ python3 -m pytest test_machine_switcher.pyを実行した結果、どちらともエラー(failed)となって赤い枠線のものがでました。

**Comment by Mnakagawa** [comment]
インターンでやってるんですよね？
手が空いてるときは出来るだけメールを返せるようにするので、
本家のIssueでわからないことはどんどん聞いてください。

**Comment by yyamma** [comment]
すみません、こちらは間違えて作成してしまいました。ありがとうございます。
